/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lavavajillas;

/**
 *
 * @author Javier
 */
public class Main extends javax.swing.JFrame {

    Lavavajillas lava1 = new Lavavajillas();
        
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        mostrarEstado();
    }

    private void mostrarEstado() {
        jTextFieldPuerta.setText(lava1.getAbierto());
        jTextFieldEnergia.setText(lava1.getEncendido());
        jTextFieldPrograma.setText(lava1.getPrograma());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAbrir = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jTextFieldPuerta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonEncender = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEnergia = new javax.swing.JTextField();
        jButtonPrograma0 = new javax.swing.JButton();
        jButtonPrograma1 = new javax.swing.JButton();
        jButtonPrograma2 = new javax.swing.JButton();
        jButtonPrograma3 = new javax.swing.JButton();
        jButtonPrograma4 = new javax.swing.JButton();
        jButtonProgramaAuto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrograma = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAbrir.setText("Abrir puerta");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cerrar puerta");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Puerta:");

        jButtonEncender.setText("Encender");
        jButtonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncenderActionPerformed(evt);
            }
        });

        jButtonApagar.setText("Apagar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        jLabel3.setText("Energía:");

        jButtonPrograma0.setText("Enjuagado");
        jButtonPrograma0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrograma0ActionPerformed(evt);
            }
        });

        jButtonPrograma1.setText("Prelavado");
        jButtonPrograma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrograma1ActionPerformed(evt);
            }
        });

        jButtonPrograma2.setText("Lavado");
        jButtonPrograma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrograma2ActionPerformed(evt);
            }
        });

        jButtonPrograma3.setText("Aclarado");
        jButtonPrograma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrograma3ActionPerformed(evt);
            }
        });

        jButtonPrograma4.setText("Secado");
        jButtonPrograma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrograma4ActionPerformed(evt);
            }
        });

        jButtonProgramaAuto.setText("Avanzar estado automáticamente");
        jButtonProgramaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProgramaAutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Programa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonProgramaAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrograma))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAbrir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCerrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPuerta)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonEncender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonApagar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEnergia))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPrograma0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrograma1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrograma2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrograma3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrograma4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEncender)
                            .addComponent(jButtonApagar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAbrir)
                            .addComponent(jButtonCerrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrograma0)
                    .addComponent(jButtonPrograma1)
                    .addComponent(jButtonPrograma2)
                    .addComponent(jButtonPrograma3)
                    .addComponent(jButtonPrograma4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProgramaAuto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        lava1.setAbierto(true);
        mostrarEstado();
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        lava1.setAbierto(false);
        mostrarEstado();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncenderActionPerformed
        lava1.setEncendido(true);
        mostrarEstado();
    }//GEN-LAST:event_jButtonEncenderActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        lava1.setEncendido(false);
        mostrarEstado();
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonPrograma0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrograma0ActionPerformed
        lava1.setPrograma(Lavavajillas.ENJUAGADO);
        mostrarEstado();
    }//GEN-LAST:event_jButtonPrograma0ActionPerformed

    private void jButtonPrograma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrograma1ActionPerformed
        lava1.setPrograma(Lavavajillas.PRELAVADO);
        mostrarEstado();
    }//GEN-LAST:event_jButtonPrograma1ActionPerformed

    private void jButtonPrograma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrograma2ActionPerformed
        lava1.setPrograma(Lavavajillas.LAVADO);
        mostrarEstado();
    }//GEN-LAST:event_jButtonPrograma2ActionPerformed

    private void jButtonPrograma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrograma3ActionPerformed
        lava1.setPrograma(Lavavajillas.ENJUAGADO);
        mostrarEstado();
    }//GEN-LAST:event_jButtonPrograma3ActionPerformed

    private void jButtonPrograma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrograma4ActionPerformed
        lava1.setPrograma(Lavavajillas.SECADO);
        mostrarEstado();
    }//GEN-LAST:event_jButtonPrograma4ActionPerformed

    private void jButtonProgramaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProgramaAutoActionPerformed
        lava1.avanzarPrograma();
        mostrarEstado();
    }//GEN-LAST:event_jButtonProgramaAutoActionPerformed
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonEncender;
    private javax.swing.JButton jButtonPrograma0;
    private javax.swing.JButton jButtonPrograma1;
    private javax.swing.JButton jButtonPrograma2;
    private javax.swing.JButton jButtonPrograma3;
    private javax.swing.JButton jButtonPrograma4;
    private javax.swing.JButton jButtonProgramaAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldEnergia;
    private javax.swing.JTextField jTextFieldPrograma;
    private javax.swing.JTextField jTextFieldPuerta;
    // End of variables declaration//GEN-END:variables
}
